version: '3.8'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=sletkov
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urlsDB
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - postgres-db:/var/lib/postgresql/data
  url-shortener:
    depends_on:
      - db
    ports:
      - "8082:8082"
    build: .
    volumes:
      - .:/usr/src/app

volumes:
  postgres-db: